### ISSUE TITLE
맥북에 vscode 기반 ipynb 가상환경 구현

### ISSUE THREAD

**Issue by J-nowcow** [Review-Mate/Review-Mate-AI#1]
* [x] 맥북에서 vscode 설치 후 가상환경 구축하기

1) 터미널 실행 후 가상환경 설치 원하는 폴더 접속
2) `python3 -m venv ./{가상환경 이름}`
3) `source {가상환경 이름}/bin/activate`
4) vscode 실행 (터미널에 code . 입력하면 바로 실행할 수 있음) 후 ipynb 파일 하나 만들고 오른쪽 위에서 커널 선택
5) ipykernel 설치같은거 vscode에서 알아서 해줌. 잘 되고 있는지 확인하고 싶으면 터미널에 `where pip` 입력하면 지금 어디에 설치하고 있는지 보여줌

* vscode teminal에 pip로 뭔가 설치하고 싶을 때는 `source {env}/bin/activate` 로 해당 가상 환경 활성화해준 다음 `where pip` 로 제대로 들어가져 있는지 확인 후 작업하기

**Comment by j-nowcow** [comment]
* [ ] 파이썬 경로 정리하기

**Comment by J-nowcow** [comment]
* [x] RuntimeError: Numpy is not available

torchvision이 3.9 이하 버전의 파이썬에서만 사용이 가능하다고 함
파이썬 다운그레이드 해주기

**Comment by J-nowcow** [comment]
맥북 배송 완료됨 -> 기존 윈도우 환경에서 구성 후 맥으로 전환하는 계획에서 바로 맥북에 구성하는 것으로 계획 변경
